[package]
name = "sudograph-tests"
version = "0.3.0"
authors = ["Jordan Last <jordan.michael.last@gmail.com>"]
edition = "2018"

# [workspace]
# members = [
#     "canisters/graphql"
# ]

[profile.release]
lto = true
opt-level = 'z'

[dependencies]
ic-agent = "0.5.2"
proptest = "1.0.0"
proptest-derive = "0.3.0"
graphql-parser = "0.3.0"
tokio = { version = "1.8.1", features = ["macros"] }
garcon = "0.2.3"
ic-cdk = "0.3.0"
serde_json = { version = "1.0.64", features = ["float_roundtrip"] }
chrono = "0.4.19"
serde = "1.0.126"